name: ocd
version: "0.1.0"
author: "Iñaki Garay <igarai@gmail.com>"
about: "A swiss army knife of utilities to work with files."
settings:
    - ArgRequiredElseHelp
subcommands:
        - mrn:
                about: "Mass ReName"
                args:
                        - verbosity:
                                takes_value: false
                                multiple_values: true
                                short: v
                                help: >
                                    Sets the verbosity level. Default is low, 
                                    one flag medium, two high, three or more 
                                    debug.
                        - silent:
                                long: silent
                                help: "Silences all output."
                        - dir:
                                takes_value: true
                                default_value: "./"
                                short: d
                                long: dir
                                help: "Run inside a given directory."
                        - parser:
                                takes_value: true
                                possible_values: ["handwritten", "lalrpop"]
                                default_value: lalrpop
                                help: Specifies with parser to use.
                        - mode:
                                takes_value: true
                                possible_values: ["a", "d", "f"]
                                default_value: f
                                short: m
                                long: mode
                                help: >
                                     Specified whether the rules are applied to directories 
                                     (b), files (f) or all (a).
                        - dry-run:
                                long: dry-run
                                help: "Do not effect any changes on the filesystem."
                        - git:
                                long: git
                                help: "Rename files by calling `git mv`"
                        - recurse:
                                short: "r"
                                long: "recurse"
                                help: "Recurse directories."
                        - undo:
                                short: u
                                long: undo
                                help: Create undo script.
                        - yes:
                                long: yes
                                help: >
                                    Do not ask for confirmation. 
                                    Useful for non-interactive batch scripts.
                        - glob:
                                takes_value: true
                                short: g
                                long: glob
                                help: |
                                     Operate only on files matching the glob pattern, e.g. `-g \"*.mp3\"`
                                     If --dir is specified as well it will be concatenated with the glob pattern.
                                     If --recurse is also specified it will be ignored.
                        - rules:
                                index: 1
                                required: true
                                takes_value: true
                                help: |
                                     The rewrite rules to apply to filenames.
                                     The value is a comma-separated list of the following rules:
                                     lc                    Lower case
                                     uc                    Upper case
                                     tc                    Title case
                                     sc                    Sentence case
                                     ccj                   Camel case join
                                     ccs                   Camel case split
                                     i <text> <position>   Insert
                                     d <from> <to>         Delete
                                     s                     Sanitize
                                     r <match> <text>      Replace
                                     sd                    Substitute space dash
                                     sp                    Substitute space period
                                     su                    Substitute space underscore
                                     dp                    Substitute dash period
                                     ds                    Substitute dash space
                                     du                    Substitute dash underscore
                                     pd                    Substitute period dash
                                     ps                    Substitute period space
                                     pu                    Substitute period under
                                     ud                    Substitute underscore dash
                                     up                    Substitute underscore period
                                     us                    Substitute underscore space
                                     ea <extension>        Extension add
                                     er                    Extension remove
                                     p <match> <pattern>   Pattern match
                                     ip                    Interactive pattern match
                                     it                    Interactive tokenize
